export enum RouterNames {
  ROOM = "ROOM_VIEW",
  SETUP = "SETUP_VIEW",
  CHANNEL_PARAMETER = "CHANNEL_PARAMETER",
  PLAY_GROUND = "PLAY_GROUND",
  PLAY_GROUND_USERS = "PLAY_GROUND_USERS",
  PLAY_GROUND_DIALOG = "PLAY_GROUND_DIALOG",
  FUNNELING = "FUNNELING",
  ATM = "ATM",
  SALTATION = "SALTATION",
  SITEMAP = "SITEMAP",
  DEVICES = "DEVICES",
  DOOR = "DOOR",
}
